# Generated by Django 5.0.6 on 2024-06-11 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_conferenceagenda_conferencesection_member_partagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partagenda',
            name='agend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='app.conferenceagenda'),
        ),
    ]
